CreateThread(function()
	blip = AddBlipForCoord(cfg.npc.x, cfg.npc.y)
	SetBlipSprite(blip, cfg.hospital.id)
	SetBlipScale(blip, cfg.hospital.size)
	SetBlipColour(blip, cfg.hospital.color)
	SetBlipAsShortRange(blip, true)
	BeginTextCommandSetBlipName('STRING')
	AddTextComponentString(cfg.hospital.name)
	EndTextCommandSetBlipName(blip)
end)
